// AUTO:ARTS:START
  const ARTS = {
    santilli_jefe_gabinete: {
      cat:'Política Nacional · Casa Rosada', fecha:'3 jul 2026', fuente:'LLANO·',
      fuenteUrl:'', foto:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Casa_Rosada_frente_a_Plaza_de_Mayo%2C_en_el_centro_de_Buenos_Aires%2C_Argentina.jpg/960px-Casa_Rosada_frente_a_Plaza_de_Mayo%2C_en_el_centro_de_Buenos_Aires%2C_Argentina.jpg',
      titulo:`Santilli asume como nuevo Jefe de Gabinete con funciones ampliadas sobre Interior`,
      bajada:`El Decreto 548/2026 formaliza la designación de Diego Santilli y fusiona la Jefatura de Gabinete con el Ministerio del Interior. Manuel Adorni dejó el cargo en medio de una investigación por presunto enriquecimiento ilícito.`,
      cuerpo:`<p>El presidente Javier Milei tomó juramento a Diego Santilli como nuevo Jefe de Gabinete de Ministros en el Salón Blanco de la Casa Rosada, poniendo fin a una etapa marcada por la salida de Manuel Adorni. La designación quedó formalizada mediante el <strong>Decreto 548/2026</strong>, publicado en el Boletín Oficial, que también aceptó la renuncia de Santilli al Ministerio del Interior para asumir sus nuevas funciones.</p><p>El cambio más significativo en la estructura de gobierno es la <strong>fusión de la Jefatura de Gabinete con el Ministerio del Interior</strong>. Milei argumentó que el área debe tener "músculo político" y que concentrar ambas carteras en una sola mano permitirá mayor coordinación de la gestión diaria del gobierno. Santilli conservará la relación con los gobernadores provinciales y sumará el vínculo directo con el Congreso.</p><p>Para completar la nueva estructura, Milei designó a <strong>Ignacio Devitt como vicejefe ejecutivo de Gabinete</strong> y a Gustavo Coria en la Vicejefatura del Interior, quien tendrá como eje la relación con las provincias, los municipios y el Congreso. Este esquema tripartito busca distribuir la carga operativa que Adorni gestionaba de forma más centralizada.</p><p>La salida de Adorni respondió a presiones crecientes por una investigación sobre presunto enriquecimiento ilícito vinculado a compras con tarjetas de empleados de su área. El propio Santilli señaló que Adorni se fue "mentalmente destruido" por problemas de índole familiar. <strong>Gobernadores de Corrientes y Chaco</strong> fueron los primeros en respaldar la designación de Santilli, aunque le marcaron agenda: obras de infraestructura y fondos de coparticipación pendientes.</p>`
    },
    radio_oncologico_acelera: {
      cat:'Salud · La Pampa', fecha:'3 jul 2026', fuente:'APN La Pampa',
      fuenteUrl:'https://apn.lapampa.gob.ar/nota/detalle/id/30246/El-Centro-Regional-Radio-Oncolgico-acelera-los-tratamientos-y-disminuye-derivaciones', foto:'https://apn.lapampa.gob.ar/images/noticias/6a46ce062831a.jpg',
      titulo:`El Radio Oncológico acelera los tratamientos y reduce las derivaciones de pacientes oncológicos`,
      bajada:`El Centro Regional Radio Oncológico La Pampa ya inició operaciones. Su director médico explica cómo la integración de servicios y la tecnología de última generación permiten reducir tiempos de tratamiento y mejorar la calidad de vida.`,
      cuerpo:`<p>El Centro Regional Radio Oncológico La Pampa inició sus operaciones y representa un avance significativo para la oncología provincial. Su director médico, <strong>Juan Pablo Sosa Caresano</strong>, explicó que la integración de servicios, la incorporación de tecnología de última generación y la atención cercana al domicilio del paciente permiten reducir tiempos de tratamiento, disminuir derivaciones y mejorar la calidad de vida.</p><p>Sosa Caresano destacó que <strong>"entre el 60% y el 70% de los pacientes necesitarán radioterapia en algún momento, y ese porcentaje puede llegar al 80%"</strong> cuando se incluyen tratamientos paliativos. Contar con un centro de estas características, enfatizó, "garantizado por la salud pública le da un enorme valor social".</p><p>El Centro reduce significativamente los tiempos entre diagnóstico e inicio del tratamiento. El oncólogo clínico puede derivar al paciente de manera inmediata, iniciando "el circuito de admisión, tomografía para la planificación y preparación del tratamiento, todo dentro de la misma institución". Tradicionalmente, los pacientes debían recorrer distintas instituciones, generando demoras que afectaban la evolución de la enfermedad.</p><p>Para quienes viven en localidades del interior o provincias vecinas, se organiza la atención <strong>concentrando estudios y tratamientos en una misma jornada</strong>, reduciendo viajes. Sosa Caresano explicó que buscan "no solo la mejor atención médica, sino también aliviar la carga" de atravesar una enfermedad oncológica. El Centro combina "tecnología de alta complejidad con una estrategia sanitaria centrada en las personas".</p>`
    },
    fibra_optica_limay_mahuida: {
      cat:'Conectividad · Interior', fecha:'3 jul 2026', fuente:'APN La Pampa',
      fuenteUrl:'https://apn.lapampa.gob.ar/nota/detalle/id/30247/Limay-Mahuida-ya-tiene-su-red-domiciliaria-de-fibra-ptica', foto:'https://apn.lapampa.gob.ar/images/multimedia/670522_whatsapp-image-2026-07-02-at-18.38.30.jpeg',
      titulo:`Limay Mahuida ya tiene fibra óptica: La Pampa llega a 73 localidades con red domiciliaria`,
      bajada:`La localidad del departamento más despoblado de Argentina sumó conectividad de fibra óptica al hogar. En 2019 solo 20 localidades pampeanas contaban con esa infraestructura; hoy son 73.`,
      cuerpo:`<p>La localidad de Limay Mahuida cuenta con nueva infraestructura de fibra óptica domiciliaria, proporcionada por <strong>Empatel</strong> y operada por Tecnowifi, el proveedor local que anteriormente ofrecía conectividad mediante radioenlaces. Con esta obra, <strong>73 localidades pampeanas cuentan con fibra óptica al hogar</strong>, en contraste con las apenas 20 que existían en 2019.</p><p>El Departamento Limay Mahuida es el <strong>menos poblado de Argentina</strong>: tiene una superficie de 10.000 kilómetros cuadrados y apenas 423 habitantes. La nueva red conecta el municipio, la escuela, la comisaría, la posta sanitaria y una antena Starlink de respaldo en el centro de salud. Los beneficios incluyen mayor estabilidad, resistencia a inclemencias climáticas y velocidad mejorada a costo accesible.</p><p>En el acto participaron el ministro de Conectividad y Modernización <strong>Antonio Curciarello</strong>, el presidente de Empatel <strong>Andrés Zulueta</strong> y la presidenta de la Comisión de Fomento <strong>María Antonia Coria</strong>. La inversión provincial forma parte del plan de expansión de conectividad que el gobierno de Ziliotto impulsa desde 2020.</p><p>La expansión de 20 a 73 localidades con fibra óptica en siete años refleja un cambio significativo en las condiciones de acceso a internet en La Pampa, particularmente en departamentos rurales donde la baja densidad poblacional históricamente desalentaba la inversión privada en infraestructura.</p>`
    },
    generacion_distribuida_pampa: {
      cat:'Energía · La Pampa', fecha:'3 jul 2026', fuente:'APN La Pampa',
      fuenteUrl:'https://apn.lapampa.gob.ar/nota/detalle/id/30237/Un-nuevo-rcord-en-generacin-distribuida-La-Pampa-supera-los-3-MW-de-potencia-instalada', foto:'https://apn.lapampa.gob.ar/images/multimedia/1338074_1.jpeg',
      titulo:`Récord: La Pampa supera los 3 MW de generación distribuida con 129 usuarios conectados a la red`,
      bajada:`La provincia alcanzó 3.311,65 kW de potencia instalada y ocupa el octavo lugar nacional en usuarios generadores. Solo en el primer semestre de 2026 se incorporó 1 MW adicional.`,
      cuerpo:`<p>La Pampa alcanzó un nuevo récord en generación distribuida: la potencia instalada superó los <strong>3 megavatios (3.311,65 kW)</strong>, con 129 usuarios generadores conectados a la red. El hito fue informado por el gobierno provincial, que destaca que solo en el primer semestre de 2026 se incorporó 1 MW adicional a la capacidad instalada.</p><p>La distribución de los 129 usuarios incluye <strong>48 residenciales, 64 comerciales, 7 organismos oficiales y 10 de otros sectores</strong>. En términos de posicionamiento nacional, La Pampa ocupa el octavo lugar en cantidad de usuarios generadores y el décimo puesto en potencia instalada, según el reporte de mayo de 2026.</p><p>El régimen de generación distribuida se implementó efectivamente hace cinco años, en 2021, dentro del <strong>Plan Estratégico de Energía</strong> impulsado por el gobernador Ziliotto en 2020. El sistema permite a los usuarios "generar parte de la energía que requieren para su consumo e inyectar a la red los eventuales excedentes, generando un ahorro en la factura del servicio eléctrico".</p><p>Como innovación de 2026, se incorporó el <strong>primer usuario generador colectivo provincial</strong>, un modelo que permite que múltiples usuarios compartan infraestructura e inversión para generar energía renovable. Esta modalidad facilita el acceso a la generación distribuida para quienes no pueden instalar paneles propios de forma individual.</p>`
    },
    super_rigi_diputados: {
      cat:'Congreso · Diputados', fecha:'3 jul 2026', fuente:'LLANO·',
      fuenteUrl:'', foto:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/144_PER%C3%8DODO_DE_SESIONES_ORDINARIAS_EN_EL_CONGRESO_DE_LA_NACI%C3%93N.jpg/960px-144_PER%C3%8DODO_DE_SESIONES_ORDINARIAS_EN_EL_CONGRESO_DE_LA_NACI%C3%93N.jpg',
      titulo:`Diputados aprobó el Super RIGI con 130 votos: el proyecto pasa al Senado`,
      bajada:`El régimen de incentivos para inversiones tecnológicas de gran escala fue aprobado en la Cámara baja con 130 votos a favor. La oposición peronista rechazó la iniciativa.`,
      cuerpo:`<p>La Cámara de Diputados aprobó el proyecto de <strong>Super RIGI</strong> con 130 votos afirmativos, 106 negativos y 7 abstenciones. El régimen de Grandes Inversiones está diseñado para atraer <strong>inversiones de escala tecnológica superiores a USD 1.000 millones</strong>. El proyecto ahora deberá ser tratado en el Senado, donde el oficialismo buscará construir los apoyos necesarios para su sanción definitiva.</p><p>El Super RIGI es una ampliación del RIGI original incorporado en la Ley Bases de 2024. La nueva versión apunta específicamente a proyectos de <strong>tecnología avanzada, data centers, energía renovable y minería de litio</strong> que superen el umbral de los mil millones de dólares. El gobierno argumenta que estas inversiones generarán empleo de calidad y divisas.</p><p>La reunión entre Milei y sus legisladores del 1 de julio definió la agenda parlamentaria del segundo semestre, con el Super RIGI, la <strong>Reforma Electoral y cambios en la Zona Fría</strong> como las tres prioridades legislativas. La Secretaría General de la Presidencia, a cargo de Karina Milei, comunicó a los legisladores las prioridades de manera directa.</p><p>La oposición peronista rechazó el Super RIGI argumentando que beneficia a grandes corporaciones internacionales en detrimento de empresas nacionales. Radicales y sectores de centroderecha votaron divididos. El debate en el Senado promete ser complejo: el oficialismo no tiene mayoría propia y deberá negociar con bloques de la UCR y aliados provinciales para asegurar la aprobación.</p>`
    },
    inflacion_junio_minimo: {
      cat:'Economía Nacional · Inflación', fecha:'3 jul 2026', fuente:'LLANO·',
      fuenteUrl:'', foto:'',
      titulo:`La inflación de junio bordearía el 1,9%: sería el mínimo en nueve meses`,
      bajada:`Consultoras privadas estiman que el IPC de junio perforará el 2% por primera vez desde septiembre de 2025. El dólar oficial cotiza a $1.510 y el BCRA interviene retirando pesos del mercado.`,
      cuerpo:`<p>La inflación de junio 2026 podría ubicarse entre el <strong>1,8% y el 1,9%</strong> según estimaciones de consultoras privadas, lo que representaría el nivel más bajo en nueve meses y la primera vez que el índice perfora el 2% desde septiembre de 2025. Los últimos datos del INDEC habían reportado una inflación de mayo del 2,1%, por lo que de confirmarse la baja, marcaría una tendencia de desaceleración.</p><p>En el mercado cambiario, el <strong>dólar oficial cotiza a $1.510</strong>, el blue a $1.525 y el dólar tarjeta a $1.963. El Banco Central concentró su intervención en la <strong>venta de letras dollar-linked</strong>, retirando pesos de circulación para moderar la presión sobre el tipo de cambio.</p><p>Las proyecciones de analistas del BCRA apuntan a una inflación de <strong>30,5% para diciembre de 2026</strong> y un dólar mayorista de $1.658 al cierre del año. La moderación inflacionaria es uno de los principales logros que el gobierno Milei busca exhibir de cara a la segunda mitad del año, en un contexto donde el ajuste fiscal y la restricción monetaria empiezan a dar resultados.</p><p>Sin embargo, analistas advierten que la <strong>presión cambiaria</strong> podría limitar la desaceleración si el dólar continúa trepando. El esquema de bandas cambiarias del BCRA fija un techo de intervención: si el tipo de cambio supera ese nivel, el Central debería vender reservas para contenerlo, lo que genera tensiones con el objetivo de acumulación de divisas.</p>`
    },
    argentina_vs_cabo_verde: {
      cat:'Mundial 2026 · Octavos', fecha:'3 jul 2026', fuente:'LLANO·',
      fuenteUrl:'', foto:'',
      titulo:`Argentina vs Cabo Verde: hoy a las 19hs en Miami, la selección debuta en octavos`,
      bajada:`La Albiceleste llega con puntaje perfecto en la fase de grupos: ganó los tres partidos (Argelia 3-0, Austria 2-0, Jordania 3-1). Messi es el goleador del equipo con 5 tantos. El rival africano es la gran sorpresa: invicto con tres empates.`,
      cuerpo:`<p>La Selección Argentina debuta hoy en los octavos de final del Mundial 2026 frente a <strong>Cabo Verde</strong>, en el Hard Rock Stadium de Miami, con inicio a las <strong>19hs hora argentina</strong>. El partido se transmite por DSports, Telefé, TyC Sports y la TV Pública.</p><p>Argentina cerró la fase de grupos como <strong>líder del Grupo J</strong> con nueve puntos en tres partidos: goleó a Argelia 3 a 0, a Austria 2 a 0 y a Jordania 3 a 1. <strong>Lionel Messi</strong> anotó cinco goles en esos tres partidos y se posiciona como uno de los favoritos al Botín de Oro del torneo. La Albiceleste mostró una versión sólida y eficiente, aunque todavía no enfrentó rivales de primer nivel.</p><p>Cabo Verde es la gran sorpresa del torneo: <strong>invicto en la primera fase con tres empates</strong> (España 0-0, Uruguay 2-2 y Arabia Saudita 0-0). Nunca ganó en el Mundial 2026 pero tampoco perdió, lo que los llevó a clasificar como segundos del Grupo H. Su fortaleza es la organización defensiva y la solidez colectiva.</p><p>Argentina llega como uno de los candidatos al título. Un paso en falso podría ser eliminatorio pero los analistas coinciden en que, salvo sorpresa, la selección debería avanzar. La clave estará en <strong>evitar la confianza excesiva</strong> ante un rival que, si bien es inferior en papel, ha demostrado ser difícil de vencer en este Mundial.</p>`
    },
    reforma_bcra_fmi: {
      cat:'Economía · Banco Central', fecha:'3 jul 2026', fuente:'LLANO·',
      fuenteUrl:'', foto:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Edificio_del_Ministerio_de_Econom%C3%ADa_de_la_Naci%C3%B3n_Argentina%2C_ubicado_sobre_la_calle_Hip%C3%B3lito_Yrigoyen%2C_frente_al_entorno_de_Plaza_de_Mayo%2C_en_la_Ciudad_de_Buenos_Aires.jpg/960px-thumbnail.jpg',
      titulo:`Milei avanza en la reforma de la Carta Orgánica del BCRA para cumplir con el FMI`,
      bajada:`Los equipos de los ministerios de Economía y Desregulación trabajan en la modificación de la Carta Orgánica del Banco Central, exigida por el FMI como condición para el acuerdo de septiembre.`,
      cuerpo:`<p>El gobierno de Javier Milei trabaja en la modificación de la <strong>Carta Orgánica del Banco Central de la República Argentina (BCRA)</strong>, una de las reformas estructurales exigidas por el FMI como condición para completar el acuerdo de septiembre de 2026. Los equipos de los ministerios de Economía y Desregulación están diseñando la propuesta de cambios.</p><p>El organismo internacional considera que la actual Carta Orgánica del BCRA contiene cláusulas que permiten al Tesoro acceder a financiamiento del banco emisor en condiciones que comprometen la estabilidad monetaria. La <strong>reforma buscaría eliminar esas cláusulas</strong> o hacerlas más restrictivas, en línea con estándares internacionales de banca central independiente.</p><p>Paralelamente, Milei reunió el 1 de julio a todos sus diputados y senadores en Casa Rosada para definir la agenda legislativa del segundo semestre. Entre las prioridades: <strong>Reforma Electoral</strong>, modificaciones al régimen de <strong>Zona Fría</strong> y el Super RIGI. La reunión fue coordinada por Karina Milei, quien consolida su rol como articuladora política del oficialismo.</p><p>La reforma del BCRA requeriría aprobación legislativa y genera resistencias en la oposición, que teme que los cambios comprometan el financiamiento de políticas sociales. El gobierno argumenta que la <strong>independencia del Central es condición necesaria</strong> para sostener la desinflación y recuperar la credibilidad monetaria ante inversores internacionales.</p>`
    },
    gobernadores_santilli: {
      cat:'Política Nacional · Gobernadores', fecha:'3 jul 2026', fuente:'LLANO·',
      fuenteUrl:'', foto:'',
      titulo:`Gobernadores de Corrientes y Chaco respaldaron a Santilli y le marcaron la agenda`,
      bajada:`Los mandatarios del nordeste argentino apoyaron al nuevo Jefe de Gabinete pero le plantearon demandas concretas: obras de infraestructura y fondos de coparticipación pendientes.`,
      cuerpo:`<p>Los gobernadores de Corrientes y Chaco fueron los primeros mandatarios provinciales en respaldar públicamente la designación de <strong>Diego Santilli como nuevo Jefe de Gabinete</strong>. Sin embargo, el apoyo vino acompañado de un mensaje claro: esperan que el nuevo funcionario tenga un rol más activo en la relación con las provincias que el que tuvo su antecesor Manuel Adorni.</p><p>Los mandatarios del nordeste le plantearon a Santilli una agenda concreta: <strong>obras de infraestructura comprometidas</strong> y no ejecutadas, fondos de coparticipación con demoras en la transferencia, y coordinación para el manejo de la emergencia hídrica en el litoral. El gobernador de Corrientes lleva meses reclamando al gobierno nacional por el estado del río Paraná.</p><p>La señal política de estos gobernadores es relevante porque ambas provincias integran el grupo de mandatarios que <strong>pueden negociar con el gobierno o con la oposición</strong> según sus intereses. Santilli, quien mantuvo la relación con gobernadores cuando era ministro del Interior, conoce bien estos circuitos.</p><p>Desde La Pampa, el gobernador <strong>Sergio Ziliotto</strong> aún no emitió declaraciones sobre la designación de Santilli. El mandatario pampeano mantiene una relación pragmática con el gobierno nacional: negocia fondos y obras sin confrontación abierta, aunque rechaza explícitamente las políticas de ajuste en educación y salud pública.</p>`
    },
    rio_quinto_lapampa_bsas: {
      cat:'Agua · Gestión', fecha:'3 jul 2026', fuente:'APN La Pampa',
      fuenteUrl:'https://apn.lapampa.gob.ar/nota/detalle/id/30235/Avanzan-las-acciones-conjuntas-entre-La-Pampa-y-Buenos-Aires-para-la-gestin-de-la-cuenca-del-ro-Quinto', foto:'https://apn.lapampa.gob.ar/images/noticias/6a453fb73ae39.jpg',
      titulo:`La Pampa y Buenos Aires avanzan en gestión conjunta de la cuenca del río Quinto`,
      bajada:`Las dos provincias coordinan acciones para el manejo hídrico de la cuenca compartida. La cooperación incluye monitoreo ambiental y uso productivo del recurso.`,
      cuerpo:`<p>La Pampa y Buenos Aires avanzan en la coordinación de acciones conjuntas para la gestión de la <strong>cuenca del río Quinto</strong>, uno de los sistemas hídricos compartidos más importantes del centro del país. La colaboración interprovincial incluye monitoreo ambiental, planificación del uso productivo del recurso y protocolos de acción ante emergencias hídricas.</p><p>El río Quinto, que atraviesa el sur de San Luis, La Pampa y el suroeste de Buenos Aires, es <strong>fuente de agua para actividades agropecuarias</strong> y ganaderas en una vasta región. La gestión coordinada es clave para evitar conflictos entre usuarios de distintas provincias y asegurar el uso sustentable del recurso ante variaciones climáticas que afectan el caudal.</p><p>La cooperación entre La Pampa y Buenos Aires tiene antecedentes en la gestión del río Colorado, donde ambas provincias integran el Comité Interjurisdiccional junto a Mendoza, Neuquén y Río Negro. El modelo de <strong>gestión colaborativa de cuencas compartidas</strong> ha demostrado ser eficaz para resolver disputas sobre agua sin recurrir a la confrontación judicial entre provincias.</p><p>En el contexto de cambio climático, la gestión hídrica interprovincial adquiere mayor relevancia: las proyecciones indican que la región pampeana enfrentará <strong>variaciones de precipitaciones más extremas</strong> en las próximas décadas, con períodos de sequía más intensos seguidos de lluvias excesivas.</p>`
    },
    creditos_bajo_riego_pampa: {
      cat:'Economía · Producción', fecha:'3 jul 2026', fuente:'APN La Pampa',
      fuenteUrl:'https://apn.lapampa.gob.ar/nota/detalle/id/30231/Lanzaron-nueva-lnea-crediticia-para-productores-del-rea-bajo-riego', foto:'https://apn.lapampa.gob.ar/images/noticias/6a45067eae700.jpg',
      titulo:`Lanzaron nueva línea crediticia para productores del área bajo riego en La Pampa`,
      bajada:`El programa apunta a impulsar la producción irrigada provincial. Los créditos están destinados a infraestructura de riego, equipamiento y capital de trabajo.`,
      cuerpo:`<p>El gobierno provincial lanzó una nueva línea crediticia destinada a <strong>productores del área bajo riego</strong> de La Pampa. El programa busca impulsar el desarrollo de la producción irrigada en la provincia, con créditos orientados a inversiones en infraestructura de riego, equipamiento y capital de trabajo.</p><p>El área bajo riego pampeana concentra producciones de <strong>alta intensidad</strong> como horticultura, fruticultura, alfalfa para exportación y cultivos forrajeros. Estas actividades tienen mayor valor por hectárea que la ganadería extensiva tradicional y generan empleo rural más estable. El fortalecimiento del riego es una de las políticas de diversificación productiva que el gobierno de Ziliotto impulsa desde su primer mandato.</p><p>La línea crediticia complementa otras iniciativas provinciales de apoyo al agro. La diversificación hacia producciones de mayor valor agregado busca <strong>reducir la dependencia de La Pampa de la ganadería bovina extensiva</strong> y aprovechar las ventajas de los suelos pampeanos para cultivos irrigados.</p><p>Los interesados en acceder a la línea deberán presentar un <strong>plan productivo</strong> ante el organismo crediticio provincial. Los plazos, tasas y montos máximos serán informados en las próximas jornadas a través de las delegaciones regionales del Ministerio de la Producción.</p>`
    },
    arata_115_aniversario: {
      cat:'Interior · Aniversario', fecha:'3 jul 2026', fuente:'APN La Pampa',
      fuenteUrl:'https://apn.lapampa.gob.ar/nota/detalle/id/30244/El-Gobierno-provincial-acompa-el-115-aniversario-de-Arata', foto:'https://apn.lapampa.gob.ar/images/multimedia/82102_whatsapp-image-2026-07-02-at-14.06.03.jpeg',
      titulo:`El gobierno provincial acompañó el 115° aniversario de Arata con actos y homenajes`,
      bajada:`La localidad del norte pampeano celebró su fundación con presencia de autoridades provinciales. Vecinos y organizaciones de la comunidad participaron de los actos centrales.`,
      cuerpo:`<p>La localidad de <strong>Arata</strong>, en el norte de La Pampa, celebró su <strong>115° aniversario de fundación</strong> con actos centrales en los que participaron autoridades provinciales, vecinos y organizaciones comunitarias. El gobierno de Sergio Ziliotto envió representantes para acompañar la conmemoración.</p><p>Arata es una pequeña localidad del Departamento Trenel, en la región norte de la provincia. Como muchas comunidades rurales pampeanas, enfrenta el desafío de la <strong>retención de población joven</strong> y el mantenimiento de servicios básicos en un contexto de emigración hacia centros urbanos mayores. Los aniversarios son oportunidades para renovar el vínculo entre el gobierno provincial y las comunidades del interior.</p><p>Los actos incluyeron homenajes a los fundadores y primeros pobladores, reconocimientos a vecinos destacados y actividades culturales organizadas por la Comisión de Fomento local. La presencia provincial es también una oportunidad para transmitir información sobre <strong>programas y servicios</strong> disponibles para las localidades del interior.</p><p>El gobierno provincial mantiene una agenda sistemática de acompañamiento a los aniversarios de las localidades pampeanas, que sirve tanto para reforzar la <strong>presencia institucional</strong> en el interior como para detectar demandas y necesidades de cada comunidad.</p>`
    },
    ucrania_ataque_drones: {
      cat:'Internacional · Conflicto', fecha:'3 jul 2026', fuente:'LLANO·',
      fuenteUrl:'', foto:'',
      titulo:`Ucrania: Rusia lanzó 496 drones y 74 misiles en ataque nocturno; al menos 21 muertos incluyendo una niña de 7 años`,
      bajada:`La Fuerza Aérea ucraniana reportó el ataque masivo. Entre las víctimas hay una niña de 7 años y casi 90 heridos. Ucrania respondió atacando una refinería rusa en Nizhni Nóvgorod.`,
      cuerpo:`<p>Rusia lanzó un ataque masivo contra Ucrania con <strong>496 drones y 74 misiles</strong>, entre ellos 24 balísticos, según informó la Fuerza Aérea ucraniana. El ataque nocturno dejó al menos <strong>21 personas muertas</strong>, incluyendo una niña de 7 años, y cerca de 90 heridas. Es uno de los ataques más intensos desde el inicio de la invasión rusa en febrero de 2022.</p><p>Las ciudades de Kyiv, Kharkiv, Odesa y varias localidades del centro y sur de Ucrania fueron blanco del ataque. Los daños incluyen infraestructura energética, edificios residenciales y equipamiento civil. La defensa antiaérea ucraniana logró <strong>interceptar una parte significativa</strong> de los proyectiles, pero el volumen del ataque superó la capacidad de respuesta en varios sectores.</p><p>Como respuesta, el Ejército ucraniano atacó la <strong>refinería de Kstovo</strong>, en la región rusa de Nizhni Nóvgorod, con drones. La instalación es una de las principales refinerías del centro de Rusia y su daño podría afectar el suministro de combustible para las operaciones militares rusas. Ucrania ha intensificado los ataques a infraestructura energética rusa como estrategia de presión.</p><p>El conflicto se prolonga sin señales claras de negociación. Ucrania sigue recibiendo <strong>apoyo militar occidental</strong>, aunque con restricciones sobre el uso de ciertas armas en territorio ruso. Rusia incrementa la presión con ataques de gran escala sobre civiles, estrategia que genera condena internacional pero no ha logrado doblar la resistencia ucraniana.</p>`
    },
    gaza_mil_dias: {
      cat:'Internacional · Conflicto', fecha:'3 jul 2026', fuente:'LLANO·',
      fuenteUrl:'', foto:'',
      titulo:`Gaza: se cumplen mil días desde el ataque de Hamás del 7-O; más de 73.000 palestinos muertos`,
      bajada:`Desde el 7 de octubre de 2023, cuando Hamás atacó Israel causando 1.200 muertos y 251 secuestrados, la ofensiva israelí en Gaza acumula más de 73.000 palestinos muertos y ha devastado el enclave.`,
      cuerpo:`<p>Este 3 de julio se cumplen aproximadamente <strong>mil días</strong> desde los ataques de Hamás del 7 de octubre de 2023, que dejaron 1.200 muertos en Israel y 251 secuestrados. La ofensiva israelí que siguió en la Franja de Gaza ha causado más de <strong>73.000 muertos</strong> según organismos internacionales y ha devastado casi por completo la infraestructura del enclave palestino.</p><p>Las familias desplazadas se cuentan por cientos de miles. Familias documentadas por agencias internacionales relatan haber sido <strong>desplazadas hasta seis veces</strong> desde el inicio del conflicto. Viven actualmente en tiendas de campaña en Deir al Balah, en condiciones que organismos humanitarios describen como infrahumanas. Una población de <strong>dos millones de personas</strong> enfrenta escasez crónica de agua, alimentos y atención médica.</p><p>Un alto el fuego negociado meses atrás no impidió que Israel continuara realizando ataques en Gaza prácticamente a diario. Las negociaciones sobre la liberación de los rehenes israelíes aún retenidos en Gaza no han llegado a un acuerdo definitivo. Qatar, Egipto y Estados Unidos han actuado como mediadores sin lograr una tregua duradera.</p><p>La situación en Gaza sigue generando <strong>divisiones profundas en la comunidad internacional</strong>. Decenas de países reconocieron al Estado Palestino. La Corte Internacional de Justicia analiza demandas por genocidio. Israel rechaza las acusaciones y defiende su derecho a la autodefensa. El conflicto no muestra señales claras de resolución tras casi tres años.</p>`
    }
  };
  // AUTO:ARTS:END